guiMode = True
colorMode = True
key1 = "na"
key2 = "na"
key3 = "na"
versionNum = "0.3 (Beta)"
externalEditor = False
aws_access_key_id = "AKIARRCEGT6ZTBPF3YIQ"
aws_secret_access_key = "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"